### ISSUE TITLE
As a data owner I want a feedback mechanism on use of open data so that I can stay up to date with where my data is being used_DASHBOARD

### ISSUE THREAD

**Issue by jonparsonsjncc** [ices-eg/WGJCDP-Cetaceans#126]

**Comment by kellymacleod** [comment]
As for #45 but this only relevant to restricted data, For open  access, counter on dashboard of downloads for each data owner?

**Comment by LynnHeeley** [comment]
dashboard counter proposed
•	There is a desire to track requests, download and use of all JCDP data, including open access.
•	There are challenges in adding conditions to use of open access data, therefore ICES have proposed a ‘unique instances of download’ approach involving recording of all open access downloads; all activated restricted downloads; and all inactive restricted downloads, split by data provider. 
•	This will be visible on the platform dashboard to all users. 
 •	This information can be used to monitor use, consider why data downloads are being refused etc. 
•	Providers will be able to monitor which data/locations/species are most regularly requested by viewing this information in the dashboard. 
![download_dashboard](https://user-images.githubusercontent.com/7250284/107246139-d8e3ab00-6a27-11eb-91df-f538a3f4dcc3.png)

**Comment by neil-ices-dk** [comment]
for public dashboard:
generic statistics (aggregation of inventory) - no of surveys, KM's of effort, temporal coverage, species coverage - records of species (mix of charts and stats)

**Comment by NikiClear** [comment]
Captured through reporting
