### ISSUE TITLE
As a data/web manager I want to ensure the coordinator gets an automated email when a data provider has uploaded their data

### ISSUE THREAD

**Issue by LynnHeeley** [ices-eg/WGJCDP-Cetaceans#156]

**Comment by neil-ices-dk** [comment]
to test

**Comment by neil-ices-dk** [comment]
@NikiClear to submit a test file and delete, just to check email trigger is working

**Comment by NikiClear** [comment]
> @NikiClear to submit a test file and delete, just to check email trigger is working

Not working - 
No email notification came to marinemammals@jncc.gov.uk when the new dataset from HiDef was submitted. 
@neil-ices-dk @cmspinto @NikkiTaylorJNCC

**Comment by neil-ices-dk** [comment]
Carlos has checked from the system side; NikiC to make a dummy file upload test to Carlos

**Comment by cmspinto** [comment]
Solved, done
