### ISSUE TITLE
As a Data user I want to be able to select data via a polygon to investigate so that I have options to easily extract data from the system / analyse data

### ISSUE THREAD

**Issue by GMDuncan** [ices-eg/WGJCDP-Cetaceans#163]
Split from #104 

Polygon "within system" not via upload - that is handled via another issue.

**Comment by neil-ices-dk** [comment]
@mehdiabbasi to implement possibility to filter by drawn rectangle on map;

**Comment by cmspinto** [comment]
Check with @mehdiabbasi when will this be implemented.

**Comment by cmspinto** [comment]
Done

https://cetaceans.ices.dk/viewonmap

![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/4b379b56-d41e-45ba-93e3-0d689203a84d)
