### ISSUE TITLE
As a data owner/manager I want to provide a DOI along with my dataset so that I can track subsequent uses of my the data

### ISSUE THREAD

**Issue by GMDuncan** [ices-eg/WGJCDP-Cetaceans#175]
OWNER provided DOI

BIG TICKET as DOIing methods vary, this is a workshop in itself

**Comment by neil-ices-dk** [comment]
see #177 same answer

**Comment by LynnHeeley** [comment]
system will need to permit input of existing DOI and a link to the existing landing page? consideration on where this information would be retained/displayed in the system (in metadata but also displayed?)

**Comment by NikiClear** [comment]
Repeat of #177 
Closed
