### ISSUE TITLE
As a data user I want a survey area footprint layer available through the map so that I can visualise the spatial and temporal timing of surveys conducted

### ISSUE THREAD

**Issue by LynnHeeley** [ices-eg/WGJCDP-Cetaceans#215]
Suggested at Steering group Meeting 26th March - awaiting priority.
@neil-ices-dk is this a polygon layer on the map? can it be filtered using the temporal and spatial filters?

**Comment by neil-ices-dk** [comment]
in its simplest form, one layer would be the footprint (spatial extent) of a specific survey area constrained by a specific time period

**Comment by NikiClear** [comment]
Delivered trough the map visualisation
closed
