### ISSUE TITLE
Suggested Check: number of calves < group size

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/WGJCDP-Cetaceans#250]
From Lucy

Additional comments:
### Validation rules: 
Number of calves cannot be greater than the group size 
If you did employ species being flagged if recorded in certain reasons, how would the region be defined? 
Outside of known range; outside of known range but with a large buffer area; even more broad than that? 
SightingAngle - I know it is limited to 3 digits, and ignore me if aerial surveys record this differently, but this should only be between 0 - 359 
RadialDistance - maybe consider flagging sightings past a certain distance 
PerpendicularDistance - maybe consider flagging sightings past a certain distance

**Comment by NikiClear** [comment]
Submitted during SG meeting: 

- Maybe sighting ranges that seem ridiculously large _from Peter Evans)_
- flag up any very rare species (e.g. North Atlantic right whale) _from Peter Evans)_
- Check for records against known OBIS distribution? _from Graeme Duncan_
- Maybe a warning if the previous Lat or Lon is vastly different from the present Lat or Lon? _from Charles Paxton_


@NikkiTaylorJNCC @neil-ices-dk @cmspinto @pcrjoana

**Comment by pcrjoana** [comment]
@pcrjoana to implement the check 1.

**Comment by pcrjoana** [comment]
@NikiClear I need a refresh here. What do you mean by "duplication in the ID fields"?

**Comment by neil-ices-dk** [comment]
@cmspinto to pick this up - thank you

**Comment by cmspinto** [comment]
All three checks have been added to the format:
 **SightingID must be unique within a file: ** http://[datsu.ices.dk/web/chkDetails.aspx?DatasetID=149&RecordID=110&groupFilterID=1951](http://datsu.ices.dk/web/chkDetails.aspx?DatasetID=149&RecordID=110&groupFilterID=1951)

**SurveyID must be unique within a file: ** http://[datsu.ices.dk/web/chkDetails.aspx?DatasetID=149&RecordID=108&groupFilterID=1949](http://datsu.ices.dk/web/chkDetails.aspx?DatasetID=149&RecordID=108&groupFilterID=1949)

 **EffortID must be unique within a file: ** http://[datsu.ices.dk/web/chkDetails.aspx?DatasetID=149&RecordID=108&groupFilterID=1950](http://datsu.ices.dk/web/chkDetails.aspx?DatasetID=149&RecordID=108&groupFilterID=1950)


Could this be checked by putting a file where one of them is repeated?

**Comment by neil-ices-dk** [comment]
> Could this be checked by putting a file where one of them is repeated?

assume you'd like @NikiClear to check that?

**Comment by NikiClear** [comment]
Duplication and number of animals checks have been tested and it seems to be working as it should - https://cetaceans.ices.dk/manage/ScreenResult/1607 

Tested the same dataset without any duplication or problems, but I got an error suggesting duplication in the SurveyID where it shouldn't be - there is only one record in the upload file. 
https://cetaceans.ices.dk/manage/ScreenResult/1609
[SCANS_BlockP_TestingNoDup.zip](https://github.com/ices-tools-dev/cetaceans/files/9469177/SCANS_BlockP_TestingNoDup.zip)

**Comment by Osanna123** [comment]
SurveyID check edited. Should work now

**Comment by NikiClear** [comment]
> SurveyID check edited. Should work now
Checked and it's working now, thanks!

**Comment by pcrjoana** [comment]
All the checks seem to be in place. Can we close this issue?

**Comment by NikkiTaylorJNCC** [comment]
> All the checks seem to be in place. Can we close this issue?

Hi @pcrjoana !! If you're happy they are covered then absolutely, we can close it.
