### ISSUE TITLE
data requests: reminder email

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/WGJCDP-Cetaceans#273]
If a data request has not been approved/rejected in system after **10 working days** then an email should be sent to the data custodian and marinemammals@ to remind them that this needs to be actions

**Comment by cmspinto** [comment]
This is an example of a kind reminder:
![image](https://user-images.githubusercontent.com/8705477/204740308-fd2da2e2-7a70-45f8-af8b-b4b31c19895a.png)

**Comment by cmspinto** [comment]
Should we start from the fresh with the reminders?

**Comment by NikiClear** [comment]
> Should we start from the fresh with the reminders?

Yes, fresh reminders make sense. Thanks Carlos!

**Comment by neil-ices-dk** [comment]
@NikiClear to make a request (and make it clear this is a test and shouldn't be answered) and then we will wait 1 week to see if the email is fired;

**Comment by cmspinto** [comment]
Solved.
