### ISSUE TITLE
log out option of manage page not working

### ISSUE THREAD

**Issue by NikiClear** [ices-eg/WGJCDP-Cetaceans#275]
The 'f) logout option on the manage page brings the user to an error page

https://cetaceans.ices.dk/manage/logout
![image](https://user-images.githubusercontent.com/87769388/188423408-499d261e-3f3b-497b-b4de-cc9ab443c0a2.png)

**Comment by cmspinto** [comment]
Done, this is working now, thanks for the heads up.
