### ISSUE TITLE
As a Data user I want to see the distribution of a particular species over time throughout the spatial area of interest ..so that I understand its coverage and the threats it faces

### ISSUE THREAD

**Issue by LynnHeeley** [ices-eg/WGJCDP-Cetaceans#37]
original id#34

Similar to #34 

Amend purpose

If survey effort, not modelled - include in Phase 2

**Comment by cmspinto** [comment]
We need to discuss the spatial and time aggregation.
Is this a table or a map?

**Comment by NikkiTaylorJNCC** [comment]
Out of scope
