### ISSUE TITLE
As a Data user I want to compare one species data to another ..so that I understand the differences

### ISSUE THREAD

**Issue by LynnHeeley** [ices-eg/WGJCDP-Cetaceans#39]
original id#36

Needs clarification - compare visually in portal? (Layering?)  Or compare offline?  Comparing what? Abundance? distribution?

**Comment by cmspinto** [comment]
Needs clarification!
This needs also an aggregation level!

**Comment by NikkiTaylorJNCC** [comment]
Unclear. Obsolete.
