### ISSUE TITLE
As a Data user I want to have access to  species specific estimates of cetacean density, distribution and population trends ..so that I can use these in my work and be reassured that there is one 'official' version of this information

### ISSUE THREAD

**Issue by LynnHeeley** [ices-eg/WGJCDP-Cetaceans#46]
original id#43

Distribution difficult to define because of erratic occurrence of species outside range. Better to produce spatial density surfaces . 

Presentation of distribution needs  thought

**Comment by cmspinto** [comment]
Potential data product of the group.

**Comment by NikkiTaylorJNCC** [comment]
Out of scope
