### ISSUE TITLE
As a Data user I want to download/view distribution (spatial) layers (for a particular time period) ..so that I can see spatially where a species has been sighted

### ISSUE THREAD

**Issue by LynnHeeley** [ices-eg/WGJCDP-Cetaceans#51]
original id#47

"True" distribution rather than Species Distribution modelling

**Comment by cmspinto** [comment]
Filter for the data download

**Comment by cmspinto** [comment]
Will this be part of a map? Will this be a product of a view?

**Comment by LynnHeeley** [comment]
Map. Steering Group Meeting 26th March agreed filters for map:  Filters – species, temporal (year and month). for reference layers see #62

**Comment by NikkiTaylorJNCC** [comment]
Complete
